name = "sneak-idx-sites-staging"
main = "sneak-sites/worker.js"
compatibility_date = "2026-08-31"
workers_dev = true

routes = [
    { pattern = "sneak-origin.coconutcoasthomes.com/*", zone_name = "coconutcoasthomes.com" },
    { pattern = "sneak-customers.coconutcoasthomes.com/*", zone_name = "coconutcoasthomes.com" },
    { pattern = "sneak-test.coconutcoasthomes.com/*", zone_name = "coconutcoasthomes.com" }
]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
SNEAK_ENV = "staging"
SNEAK_SERVING_URL = "https://sneak-idx-worker-staging.bonitaspringsrealtors.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "sneak-idx-staging"
database_id = "6b91eeca-d65f-434c-a49f-419dff98285f"
migrations_dir = "migrations"
