# wrangler.sneak-member.toml
# Dedicated Configuration for SNEAK IDX Staging Member Self-Service Portal

name = "sneak-idx-member-staging"
main = "sneak-member/worker.js"
compatibility_date = "2026-09-01"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
SNEAK_ENV = "staging"
EMAIL_FROM = "CCOR IDX Plug-in <no-reply@ccorealtors.org>"

[[d1_databases]]
binding = "DB"
database_name = "sneak-idx-staging"
database_id = "6b91eeca-d65f-434c-a49f-419dff98285f"
migrations_dir = "migrations"
