# wrangler.sneak-admin.toml
# Dedicated Configuration for SNEAK IDX Staging Private Administration Portal

name = "sneak-idx-admin-staging"
main = "sneak-admin/worker.js"
compatibility_date = "2024-01-01"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
SNEAK_ENV = "staging"

[[d1_databases]]
binding = "DB"
database_name = "sneak-idx-staging"
database_id = "6b91eeca-d65f-434c-a49f-419dff98285f"
migrations_dir = "migrations"

[[services]]
binding = "MEMBER_WORKER"
service = "sneak-idx-member-staging"

